<a href="https://colab.research.google.com/github/AbdulKaiz-007/Formula-1/blob/main/Fuel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [32]:
df=pd.read_csv('fuel.csv')

In [35]:
df.head(7)

,vehicle_id,year,make,model,class,drive,transmission,transmission_type,engine_index,engine_descriptor,...,hours_to_charge_ac_240v,composite_city_mpg,composite_highway_mpg,composite_combined_mpg,range_ft1,city_range_ft1,highway_range_ft1,range_ft2,city_range_ft2,highway_range_ft2
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9001,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9005,(FFS) CA model,...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9002,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9006,(FFS) CA model,...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,NaN,1830,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
5,28426,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,NaN,1880,(FFS) CA model,...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
6,27549,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,NaN,1831,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38113 entries, 0 to 38112
Data columns (total 81 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   vehicle_id                         38113 non-null  int64
 1   year                               38113 non-null  int64
 2   make                               38113 non-null  object
 3   model                              38113 non-null  object
 4   class                              38113 non-null  object
 5   drive                              36924 non-null  object
 6   transmission                       38102 non-null  object
 7   transmission_type                  15045 non-null  object
 8   engine_index                       38113 non-null  int64
 9   engine_descriptor                  22693 non-null  object
 10  engine_cylinders                   37977 non-null  float64
 11  engine_displacement                37979 non-null  float64
 12  turbocharger                       5239 non-null   object
 13  supercharger                       0 non-null      float64
 14  fuel_type                          38113 non-null  object
 15  fuel_type_1                        38113 non-null  object
 16  fuel_type_2                        0 non-null      float64
 17  city_mpg_ft1                       38113 non-null  int64
 18  unrounded_city_mpg_ft1             38113 non-null  float64
 19  city_mpg_ft2                       38113 non-null  int64
 20  unrounded_city_mpg_ft2             38113 non-null  float64
 21  city_gasoline_consumption_cd       38113 non-null  float64
 22  city_electricity_consumption       38113 non-null  float64
 23  city_utility_factor                38113 non-null  float64
 24  highway_mpg_ft1                    38113 non-null  int64
 25  unrounded_highway_mpg_ft1          38113 non-null  float64
 26  highway_mpg_ft2                    38113 non-null  int64
 27  unrounded_highway_mpg_ft2          38113 non-null  float64
 28  highway_gasoline_consumption_cd    38113 non-null  float64
 29  highway_electricity_consumption    38113 non-null  float64
 30  highway_utility_factor             38113 non-null  float64
 31  unadjusted_city_mpg_ft1            38113 non-null  float64
 32  unadjusted_highway_mpg_ft1         38113 non-null  float64
 33  unadjusted_city_mpg_ft2            38113 non-null  float64
 34  unadjusted_highway_mpg_ft2         38113 non-null  float64
 35  combined_mpg_ft1                   38113 non-null  int64
 36  unrounded_combined_mpg_ft1         38113 non-null  float64
 37  combined_mpg_ft2                   38113 non-null  int64
 38  unrounded_combined_mpg_ft2         38113 non-null  float64
 39  combined_electricity_consumption   38113 non-null  float64
 40  combined_gasoline_consumption_cd   38113 non-null  float64
 41  combined_utility_factor            38113 non-null  float64
 42  annual_fuel_cost_ft1               38113 non-null  int64
 43  annual_fuel_cost_ft2               38113 non-null  int64
 44  gas_guzzler_tax                    964 non-null    object
 45  save_or_spend_5_year               38113 non-null  int64
 46  annual_consumption_in_barrels_ft1  38113 non-null  float64
 47  annual_consumption_in_barrels_ft2  38113 non-null  float64
 48  tailpipe_co2_ft1                   38113 non-null  int64
 49  tailpipe_co2_in_grams_mile_ft1     38113 non-null  float64
 50  tailpipe_co2_ft2                   38113 non-null  int64
 51  tailpipe_co2_in_grams_mile_ft2     38113 non-null  float64
 52  fuel_economy_score                 38113 non-null  int64
 53  ghg_score                          38113 non-null  int64
 54  ghg_score_alt_fuel                 38113 non-null  int64
 55  my_mpg_data                        38113 non-null  object
 56  x2d_passenger_volume               38113 non-null  int64
 57  x2d_luggage_volume                 38113 non-null  int64
 58  x4d_passenger_volume               38113 non-null  int64
 59  x4d_luggage_volume                 38113 non-null  int64
 60  hatchback_passenger_volume         38113 non-null  int64
 61  hatchback_luggage_volume           38113 non-null  int64
 62  start_stop_technology              0 non-null      float64
 63  alternative_fuel_technology        3047 non-null   object
 64  electric_motor                     0 non-null      float64
 65  manufacturer_code                  0 non-null      float64
 66  gasoline_electricity_blended_cd    38113 non-null  bool
 67  vehicle_charger                    0 non-null      float64
 68  alternate_charger                  0 non-null      float64
 69  hours_to_charge_120v               38113 non-null  int64
 70  hours_to_charge_240v               38113 non-null  float64
 71  hours_to_charge_ac_240v            38113 non-null  float64
 72  composite_city_mpg                 38113 non-null  int64
 73  composite_highway_mpg              38113 non-null  int64
 74  composite_combined_mpg             38113 non-null  int64
 75  range_ft1                          38113 non-null  int64
 76  city_range_ft1                     38113 non-null  float64
 77  highway_range_ft1                  38113 non-null  float64
 78  range_ft2                          0 non-null      float64
 79  city_range_ft2                     38113 non-null  float64
 80  highway_range_ft2                  38113 non-null  float64
dtypes: bool(1), float64(39), int64(28), object(13)
memory usage: 23.3+ MB

In [37]:
df.shape

(38113, 81)

In [47]:
columns = []
for col in df.columns:
    if(df[col].nunique() == 0):
        columns.append(col)
columns

['supercharger',
 'fuel_type_2',
 'start_stop_technology',
 'electric_motor',
 'manufacturer_code',
 'vehicle_charger',
 'alternate_charger',
 'range_ft2']

In [48]:
df.drop(columns=columns, inplace = True)

In [49]:
df.shape

(38113, 73)

In [50]:
columns = []
for col in df.columns:
    if(df[col].isna().sum() > 0):
        columns.append(col)
columns

['drive',
 'transmission',
 'transmission_type',
 'engine_descriptor',
 'engine_cylinders',
 'engine_displacement',
 'turbocharger',
 'gas_guzzler_tax',
 'alternative_fuel_technology']

In [51]:
df_missing = df[columns]
(df_missing.isna().sum() / len(df)) * 100

drive                           3.119670
transmission                    0.028862
transmission_type              60.525280
engine_descriptor              40.458636
engine_cylinders                0.356834
engine_displacement             0.351586
turbocharger                   86.254034
gas_guzzler_tax                97.470679
alternative_fuel_technology    92.005353
dtype: float64

In [52]:
columns = []
for col in df_missing.columns:
    if(((df_missing[col].isna().sum() / len(df)) * 100 ) > 40):
        columns.append(col)
columns

['transmission_type',
 'engine_descriptor',
 'turbocharger',
 'gas_guzzler_tax',
 'alternative_fuel_technology']

In [53]:
df.drop(columns=columns, inplace = True)

In [54]:
df.shape

(38113, 68)

In [55]:
columns = []
for col in df.columns:
    if(df[col].isna().sum() > 0):
        columns.append(col)
columns

['drive', 'transmission', 'engine_cylinders', 'engine_displacement']

In [56]:
(df_missing.isna().sum()/ len(df)) * 100

drive                           3.119670
transmission                    0.028862
transmission_type              60.525280
engine_descriptor              40.458636
engine_cylinders                0.356834
engine_displacement             0.351586
turbocharger                   86.254034
gas_guzzler_tax                97.470679
alternative_fuel_technology    92.005353
dtype: float64

In [57]:
df.head()

,vehicle_id,year,make,model,class,drive,transmission,engine_index,engine_cylinders,engine_displacement,...,hours_to_charge_240v,hours_to_charge_ac_240v,composite_city_mpg,composite_highway_mpg,composite_combined_mpg,range_ft1,city_range_ft1,highway_range_ft1,city_range_ft2,highway_range_ft2
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,9001,6.0,2.5,...,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,9005,6.0,2.5,...,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,9002,4.0,2.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,9006,4.0,2.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,1830,4.0,2.5,...,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0

In [58]:
from sklearn.impute import KNNImputer

df_numeric = df.select_dtypes(include='number')
imputer = KNNImputer(n_neighbors=20)
df_imputed = pd.DataFrame(imputer.fit_transform(df_numeric), columns=df_numeric.columns)

In [59]:
df = df_imputed
df.isna().sum()

vehicle_id                           0
year                                 0
engine_index                         0
engine_cylinders                     0
engine_displacement                  0
city_mpg_ft1                         0
unrounded_city_mpg_ft1               0
city_mpg_ft2                         0
unrounded_city_mpg_ft2               0
city_gasoline_consumption_cd         0
city_electricity_consumption         0
city_utility_factor                  0
highway_mpg_ft1                      0
unrounded_highway_mpg_ft1            0
highway_mpg_ft2                      0
unrounded_highway_mpg_ft2            0
highway_gasoline_consumption_cd      0
highway_electricity_consumption      0
highway_utility_factor               0
unadjusted_city_mpg_ft1              0
unadjusted_highway_mpg_ft1           0
unadjusted_city_mpg_ft2              0
unadjusted_highway_mpg_ft2           0
combined_mpg_ft1                     0
unrounded_combined_mpg_ft1           0
combined_mpg_ft2                     0
unrounded_combined_mpg_ft2           0
combined_electricity_consumption     0
combined_gasoline_consumption_cd     0
combined_utility_factor              0
annual_fuel_cost_ft1                 0
annual_fuel_cost_ft2                 0
save_or_spend_5_year                 0
annual_consumption_in_barrels_ft1    0
annual_consumption_in_barrels_ft2    0
tailpipe_co2_ft1                     0
tailpipe_co2_in_grams_mile_ft1       0
tailpipe_co2_ft2                     0
tailpipe_co2_in_grams_mile_ft2       0
fuel_economy_score                   0
ghg_score                            0
ghg_score_alt_fuel                   0
x2d_passenger_volume                 0
x2d_luggage_volume                   0
x4d_passenger_volume                 0
x4d_luggage_volume                   0
hatchback_passenger_volume           0
hatchback_luggage_volume             0
hours_to_charge_120v                 0
hours_to_charge_240v                 0
hours_to_charge_ac_240v              0
composite_city_mpg                   0
composite_highway_mpg                0
composite_combined_mpg               0
range_ft1                            0
city_range_ft1                       0
highway_range_ft1                    0
city_range_ft2                       0
highway_range_ft2                    0
dtype: int64

In [60]:
from sklearn.ensemble import RandomForestRegressor

X = df.drop(columns=['fuel_economy_score'])
y = df['fuel_economy_score']

rf = RandomForestRegressor()
rf.fit(X, y)
feature_importances = pd.Series(rf.feature_importances_, index=X.columns)
sorted_importances = feature_importances.sort_values(ascending=False)
top_20_features = sorted_importances.head(20)

top_20_features

ghg_score                            0.988560
tailpipe_co2_ft1                     0.005580
year                                 0.004149
unadjusted_city_mpg_ft1              0.001144
unrounded_combined_mpg_ft1           0.000210
unrounded_city_mpg_ft1               0.000076
combined_mpg_ft1                     0.000052
city_mpg_ft1                         0.000032
vehicle_id                           0.000022
unadjusted_highway_mpg_ft1           0.000020
unrounded_highway_mpg_ft1            0.000018
engine_index                         0.000015
tailpipe_co2_in_grams_mile_ft1       0.000014
annual_consumption_in_barrels_ft1    0.000011
highway_mpg_ft1                      0.000011
highway_electricity_consumption      0.000006
unadjusted_highway_mpg_ft2           0.000006
combined_electricity_consumption     0.000005
annual_fuel_cost_ft1                 0.000005
annual_consumption_in_barrels_ft2    0.000005
dtype: float64

In [62]:
df_top_20 = df[[
'tailpipe_co2_ft1',
'unadjusted_city_mpg_ft1',
'unrounded_combined_mpg_ft1',
'combined_mpg_ft1',
'city_mpg_ft1',
'unadjusted_highway_mpg_ft1',
'engine_index',
'annual_consumption_in_barrels_ft1',
'highway_mpg_ft1',
'tailpipe_co2_in_grams_mile_ft1',
'combined_electricity_consumption',
'annual_fuel_cost_ft1',
'city_electricity_consumption',
'composite_highway_mpg',
'annual_consumption_in_barrels_ft2','fuel_economy_score']]

In [63]:
X = df_top_20.drop(columns=['fuel_economy_score'])
y = df_top_20['fuel_economy_score']

In [65]:
X.shape ,  y.shape

((38113, 15), (38113,))